#!/bin/bash

# ============================================================================
# INSTRUÇÕES DE DEPLOY MANUAL - Correção de Comissões para Clientes Existentes
# ============================================================================
# 
# Este script contém as instruções passo a passo para fazer deploy em produção
# Execute cada comando manualmente no seu terminal
#
# ============================================================================

echo "🚀 DEPLOY - Correção de Comissões para Clientes Existentes"
echo "=========================================================="
echo ""
echo "PASSO 1: Construir Docker Image (na sua máquina local)"
echo "=========================================================="
echo ""
echo "Execute este comando:"
echo ""
echo "  docker build --platform linux/amd64 -t simuladores-app:latest ."
echo ""
echo "Aguarde até que o build termine (pode levar 2-3 minutos)"
echo ""
read -p "Pressione ENTER quando o build terminar..."

echo ""
echo "PASSO 2: Salvar Docker Image"
echo "============================="
echo ""
echo "Execute este comando:"
echo ""
echo "  docker save simuladores-app:latest -o simuladores-app-latest.tar"
echo ""
echo "Aguarde até que o arquivo seja criado (pode levar 1-2 minutos)"
echo ""
read -p "Pressione ENTER quando o arquivo for criado..."

echo ""
echo "PASSO 3: Transferir Image para Servidor"
echo "========================================"
echo ""
echo "Execute este comando:"
echo ""
echo "  scp -P 22 simuladores-app-latest.tar root@10.10.50.246:/tmp/"
echo ""
echo "Digite a senha do servidor quando solicitado"
echo "Aguarde até que a transferência termine (pode levar 5-10 minutos)"
echo ""
read -p "Pressione ENTER quando a transferência terminar..."

echo ""
echo "PASSO 4: Fazer Deploy no Servidor"
echo "=================================="
echo ""
echo "Execute este comando:"
echo ""
echo "  ssh root@10.10.50.246"
echo ""
echo "Depois, no servidor, execute os comandos abaixo um por um:"
echo ""
echo "  1. Parar containers antigos:"
echo "     docker-compose -f /root/docker-compose.prod.yml down"
echo ""
echo "  2. Carregar nova image:"
echo "     docker load -i /tmp/simuladores-app-latest.tar"
echo ""
echo "  3. Iniciar containers:"
echo "     docker-compose -f /root/docker-compose.prod.yml up -d"
echo ""
echo "  4. Aguardar 10 segundos:"
echo "     sleep 10"
echo ""
echo "  5. Verificar status:"
echo "     docker-compose -f /root/docker-compose.prod.yml ps"
echo ""
echo "  6. Testar health check:"
echo "     curl -s http://localhost:3009/api/health"
echo ""
echo "  7. Sair do servidor:"
echo "     exit"
echo ""
read -p "Pressione ENTER quando terminar os comandos no servidor..."

echo ""
echo "PASSO 5: Verificar Deploy"
echo "========================="
echo ""
echo "Execute este comando para verificar se a aplicação está respondendo:"
echo ""
echo "  curl -s http://10.10.50.246:3009/api/health | jq ."
echo ""
echo "Se receber uma resposta com status 'ok', o deploy foi bem-sucedido!"
echo ""
read -p "Pressione ENTER para finalizar..."

echo ""
echo "✅ DEPLOY CONCLUÍDO!"
echo ""
echo "Mudanças implementadas:"
echo "  ✅ Comissões calculadas apenas sobre diferença de valor para clientes existentes"
echo "  ✅ Se diferença for negativa, comissão = R$ 0,00"
echo "  ✅ Checkbox duplicado removido em InternetRadioCalculator"
echo "  ✅ Null checks adicionados em todas as calculadoras"
echo ""
echo "Acesse: http://10.10.50.246:3009"
echo ""
